cls
}
$i++
cls
 ##############################
 # Add Required Type Libraries
     [System.Reflection.Assembly]::LoadFrom((Join-Path (Get-Item $env:SMS_ADMIN_UI_PATH).Parent.FullName "Microsoft.ConfigurationManagement.ManagementProvider.dll")) | Out-Null
     [System.Reflection.Assembly]::LoadFrom((Join-Path (Get-Item $env:SMS_ADMIN_UI_PATH).Parent.FullName "Microsoft.ConfigurationManagement.ApplicationManagement.dll")) | Out-Null
     [System.Reflection.Assembly]::LoadFrom((Join-Path (Get-Item $env:SMS_ADMIN_UI_PATH).Parent.FullName "Microsoft.ConfigurationManagement.ApplicationManagement.Extender.dll")) | Out-Null
     [System.Reflection.Assembly]::LoadFrom((Join-Path (Get-Item $env:SMS_ADMIN_UI_PATH).Parent.FullName "Microsoft.ConfigurationManagement.ApplicationManagement.MsiInstaller.dll")) | Out-Null
##############################
C:
CD 'C:\Program Files (x86)\Microsoft Endpoint Manager\AdminConsole\bin'
Import-Module ".\ConfigurationManager.psd1"
##############################
$ADGroups = Get-ADGroup -Filter *
$ADGroups.name | sort | Set-Content 'D:\Projects\ActiveDirectory\AD_Group_Names.txt'
##############################
Start-Sleep -Milliseconds 500
Set-Location XX1:
CD XX1:
##############################
$ADate = Get-Date -Format "yyyy_MM-dd"


$Collections = 'RemoteLocale Users',
'SDG-.Net 4.8 Users',
'SDG-Adobe Acrobat Reader DC MUI Users',
'SDG-Adobe Reader 2017 Users',
'SDG-McAfee Replacement',
'SDG-Power BI Desktop RS IT Users Only',
'SDG-TESTING',
'SDG-Veriphone driver',
'SDG-Windows 10 Admin Kit 1803 Users',
'SDG-Verifone Driver Users',
'SDG-.NET Framework 4.8 Users',
'SDG-Accellion Kiteworks Users',
'SDG-AccessPad Users',
'SDG-ACHPro Users',
'SDG-Acumen 2016.02 Users',
'SDG-All Software Users',
'SDG-ALM Microsoft Excel Addin Users',
'SDG-ALS OCRA Test Users',
'SDG-Ambit Optimist Users',
'SDG-Anypoint Studio 6.6.10 Users',
'SDG-Anypoint Studio 7.11.1 Users',
'SDG-AppNeta Users',
'SDG-Articulate 360 Users',
'SDG-Attachmate Reflection Users',
'SDG-AutoCAD LT Users',
'SDG-Azul Zulu JDK Users',
'SDG-Bloomberg Terminal Users',
'SDG-Bomgar Representative Console Users',
'SDG-Boson Exam Environment Users',
'SDG-RemoteLocale Capture Users',
'SDG-Bridger Insight XG Smart Client Users',
'SDG-Calculator Users',
'SDG-Camtasia 2019 Users',
'SDG-Camtasia 2022 Users',
'SDG-Camtasia Studio Users',
'SDG-Capital IQ Office Plug-in 9.5 Users',
'SDG-Capital IQ Office Plug-in Users',
'SDG-Cisco Ironport Users',
'SDG-Cisco Supervisor Users',
'SDG-Cisco Unified Personal Communicator Users',
'SDG-Citrix Receiver 4.9 Users',
'SDG-Citrix Receiver Users',
'SDG-ClickYes Users',
'SDG-CMTrace',
'SDG-Cofense Reporter Users',
'SDG-ConfigMgr Task Sequence Monitor Users',
'SDG-Copado Selenium Recorder Users',
'SDG-CRAWiz Users',
'SDG-Data-Tier App Framework Users',
'SDG-DatawatchMonarch_14.2 Users',
'SDG-DAX Studio Users',
'SDG-Dell Display Manager Users',
'SDG-DemandTools Users',
'SDG-DM9 Java 8u77 Users',
'SDG-Duo Authentication for Windows Logon x64 Users',
'SDG-DYMO Label Users',
'SDG-Eclipse Neon Users',
'SDG-Empyrean ALM Users',
'SDG-APPLICATION01 Users',
'SDG-Entrust Identity Guard Soft Token Users',
'SDG-Epson TM-S9000 Multifuntion APP2 Device Users',
'SDG-eSignal Users',
'SDG-EVP Office Users',
'SDG-ExtraXtreme9.1 Test Session Users',
'SDG-ExtraXtreme9.1 Training Session Users',
'SDG-ExtraXtreme9.1 Users',
'SDG-ExtraXtreme9.3 Users',
'SDG-FactSet 2016.31 Users',
'SDG-FactSet Users',
'SDG-FECFile Users',
'SDG-FileZilla FTP Client Users',
'SDG-FlexTerm NOC Sessions Users',
'SDG-FlexTerm RDARS Users',
'SDG-FlexTerm Test Session Users',
'SDG-FOSCAM HD IP Camera Users',
'SDG-Gasper Exchange Users',
'SDG-Git for Windows 2.25 Users',
'SDG-GoldPoint Users',
'SDG-Google Earth Pro Users',
'SDG-Handbrake Users',
'SDG-HEIF-Image-Extensions Users',
'SDG-HP DisplayLink Users',
'SDG-HP Quality Center Excel AddIn 12.55 Users',
'SDG-HPE Unified Functional Testing Users',
'SDG-HxD Users',
'SDG-Hyland ActiveX Users',
'SDG-Hyland AppEnabler Users',
'SDG-Image Centre Users',
'SDG-InfoAcess and OnBase Admin Reporting Users',
'SDG-IntelliJ IDEA Community Edition Users',
'SDG-InterSystems Cache ODBC32',
'SDG-InterSystems Cache ODBC64',
'SDG-ISIS Users',
'SDG-Katalon Studio Users',
'SDG-McAfee Client Proxy Users',
'SDG-Symantec DLP Users',
'SDG-McAfee Encryption Users',
'SDG-McAfee Endpoint Security Platform Users',
'SDG-McAfee FramePackage Users',
'SDG-Micro Focus Reflection Desktop COWAM Users',
'SDG-Micro Focus Reflection Desktop PepPlus Users',
'SDG-Micro Focus Reflection Desktop Test Users',
'SDG-Micro Focus Reflection Desktop Training Users',
'SDG-Micro Focus Reflection Desktop Users',
'SDG-Microsoft Access Database Engine 2010 Users',
'SDG-Microsoft Access Database Engine 2016 Users',
'SDG-Microsoft Access Runtime 2010 x86 Users',
'SDG-Microsoft Command Line Utilities 15 for SQL Server Users',
'SDG-Microsoft CPlus 2005 x32 Users',
'SDG-Microsoft CPlus 2008 x32 Users',
'SDG-Microsoft CPlus 2010 x32 Users',
'SDG-Microsoft CPlus 2012 Users',
'SDG-Microsoft CPlus 2015 x32 Users',
'SDG-Microsoft CPlus 2015 x64 Users',
'SDG-Microsoft CPlus 2015-2022 Users',
'SDG-Microsoft ODBC Driver 17 for SQL Server Users',
'SDG-Microsoft Office 2016 x64 Users',
'SDG-Microsoft Power BI Desktop Users',
'SDG-Microsoft SQL Server 2008 Native Client Users',
'SDG-Microsoft SQL Server 2012 ADOMD.NET 32bit Users',
'SDG-Microsoft SQL Server 2012 Analysis Management Objects Users',
'SDG-Microsoft SQL Server 2016 ADOMD.NET 32bit Users',
'SDG-Microsoft SQL Server 2016 ADOMD.NET Users',
'SDG-Microsoft SQL Server 2016 Analysis Management Objects Users',
'SDG-MicrosoftSQLServer2012AnalysisManagementObjects32bit Users',
'SDG-MicrosoftSQLServer2016AnalysisManagementObjects32bit Users',
'SDG-Monarch 2020 Users',
'SDG-Monarch Users',
'SDG-Morningstar Add-in 6.12.21 Users',
'SDG-Morningstar Add-in 6.4.24 Users',
'SDG-NotepadPlusPlus 7.4.2 Users',
'SDG-Notepadplusplus 7.5.1 Users',
'SDG-NotifyDisableIEOptions Users',
'SDG-OnBase Test Users',
'SDG-Open XML SDK 2.5 for Microsoft Office Users',
'SDG-OpenJDK 11 Users',
'SDG-Optimist RDP Users',
'SDG-Oracle SQL Developer Users',
'SDG-OrgPublisher PluginX Users',
'SDG-PayPlus BSA Test Users',
'SDG-PayPlus GFX Test Users',
'SDG-PayPlus PM Client Test Users',
'SDG-PeopleSoft PeopleTools ODBC Users',
'SDG-PF Batch Export Users',
'SDG-Plotagon Studio Users',
'SDG-Polycom RealPresence Desktop',
'SDG-Power BI Desktop RS May 2022 Users',
'SDG-Power BI Desktop RS Users',
'SDG-Power BI Desktop Users',
'SDG-PowerShell Studio 2023 Users',
'SDG-Printer Installer Client Users',
'SDG-Privilege Management for Windows Users',
'SDG-PRM 7.1 Users',
'SDG-PuTTY release 0.66 Users',
'SDG-Python Users',
'SDG-Qlik Sense Users',
'SDG-R for Windows 3.4.2 Users',
'SDG-R for Windows 4.1.0 Users',
'SDG-R for Windows Users',
'SDG-Rapid7 Insight Agent Users',
'SDG-Razor SQL 64 bit Users',
'SDG-RazorSQL 9.0.5 Users',
'SDG-RazorSQL 9.5 Users',
'SDG-RazorSQL Users',
'SDG-reaConverter 7 Pro Users',
'SDG-Reflector 2 Users',
'SDG-Remote Server Administration Tools Users',
'SDG-RStudio 1.1.383 Users',
'SDG-RStudio Users',
'SDG-SafeNet Authentication Client 10.8C AKL Users',
'SDG-SageLamp ZoomIn Users',
'SDG-Salesforce Data Loader Users',
'SDG-Salesforce DevTools Users',
'SDG-APP1 Users',
'SDG-SAS Deployment Manager Users',
'SDG-SCCM Console Users',
'SDG-SecureCRT Users',
'SDG-SecureCRTSecureFX Users',
'SDG-SecureFX Users',
'SDG-SentinelOne Users',
'SDG-SkyHigh Client Proxy Users',
'SDG-SnagIt 12.4 Users',
'SDG-SnagIt 2018 Users',
'SDG-Snagit 2023 Users',
'SDG-Snip and Sketch Users',
'SDG-SoapUI 5.3 32bit Users',
'SDG-SoapUI 5.3 64bit Users',
'SDG-Sourcetree Users',
'SDG-SQL Management Studio 17.2 Users',
'SDG-SQL Server Mgt Studio 18 Users',
'SDG-SQL Sys CLR Types Users',
'SDG-Stata 16 Users',
'SDG-SYSB for Attachmate Extra Users',
'SDG-SYSB for Reflection Desktop Users',
'SDG-Tableau 10.0 Users',
'SDG-Tableau 10.3 Oracle Driver Users',
'SDG-Tableau 10.3 Users',
'SDG-Tableau 2018 Users',
'SDG-Tableau 2021.4.2 Users',
'SDG-Tableau Creator Users',
'SDG-Tableau Reader 10.1 Users',
'SDG-Tableau Reader 10.3 Users',
'SDG-Tableau Reader Users',
'SDG-Tableau Users',
'SDG-TCC Client Users',
'SDG-Teams',
'SDG-APP2 H Users',
'SDG-Test Users',
'SDG-Thomson Reuters ONESOURCE Excel Addin Users',
'SDG-Trellix Agent Users',
'SDG-Trust Wealth Mgmt URLs Users',
'SDG-TrustDesk Users',
'SDG-Trusteer Endpoint Protection Users',
'SDG-Turboswift Users',
'SDG-UFT Add-in for ALM Users',
'SDG-UniConvertor Users',
'SDG-VBI Recorder Users',
'SDG-Veritas Enterprise Vault Discovery Accelerator Client Users',
'SDG-Veritas Enterprise Vault Users',
'SDG-Vid-Center Users',
'SDG-Video Inspector 13.0.5 Users',
'SDG-VirtualBox 7.0.6 Users',
'SDG-VirtualBox Users',
'SDG-Visio365 Users',
'SDG-Visual Studio Enterprise 2017 Users',
'SDG-WalkMe Editor Users',
'SDG-WebEx Productivity Tools Users',
'SDG-WinZip 25 Users',
'SDG-WinZip 26 Users',
'SDG-Wireshark Users',
'SDG-Workshare Professional Users',
'SDG-XMLSpy 2017 Ent Users',
'SDG-XMLSpy 2017 Pro Users',
'SDG-XMLSpy 2018 Ent Users',
'SDG-XMLSpy 2018 Pro Users',
'SDG-XMLSpy Users',
'SDG-Zephyr StyleADVISOR Users',
'SDG-Zoom Users',
'SDG-7Zip 64bit Users',
'SDG-Able 2 Extract Users',
'SDG-Access-to-MySQL Users',
'SDG-ACL for Windows Users',
'SDG-Actimize Visual Modeler Users',
'SDG-Acumen 2019.02 Users',
'SDG-AddVantage Reference Library Users',
'SDG-Adherence Log Templates Users',
'SDG-Adobe Acrobat 2017 Pro Users',
'SDG-Adobe Acrobat 2017 Standard Users',
'SDG-Adobe Acrobat Reader DC Users',
'SDG-Adobe Digital Editions Users',
'SDG-AMS360 Users',
'SDG-Anaconda Users',
'SDG-Anypoint Studio 7 Users',
'SDG-Anypoint Studio DOMAIN Users',
'SDG-APRWin 6.2 Users',
'SDG-AssetWriter Users',
'SDG-Audacity Users',
'SDG-AutoCAD LT 2023 Users',
'SDG-Azure Data Studio 1.25.1 Users',
'SDG-BIG-IP Edge Client Users',
'SDG-Broadgun pdfMachine Users',
'SDG-Business Views Microsoft Excel Add-In for ALM 17.0 Users',
'SDG-Camtasia 2023 Users',
'SDG-Camtasia Studio Library Modules Users',
'SDG-Census 2010 Users',
'SDG-Citrix Workspace 2002 Users',
'SDG-Claims Manager Client Users',
'SDG-CMGR Users',
'SDG-Crystal Reports Viewer XI Users',
'SDG-CU Device Manager Users',
'SDG-D1 Bookmark Users',
'SDG-D1 Bookmark-Training Users',
'SDG-DART Printing Users',
'SDG-DAX Studio 3 Users',
'SDG-DBeaver Users',
'SDG-DemandTools V Users',
'SDG-Digital Express Reports Users',
'SDG-DSS Trips 2019 Users',
'SDG-DYMO Label 8.7.4 Users',
'SDG-Eclipse Enterprise Java 4.18.0 Users',
'SDG-e-Form RS Users',
'SDG-Encompass360 Users',
'SDG-EVP Office 8.5.1 Users',
'SDG-FileMaker Pro Users',
'SDG-Financial Reporting Studio Users',
'SDG-Firefox Users',
'SDG-FIS Authenticator Users',
'SDG-Five9 Connectivity Assessment Test Users',
'SDG-Five9 Contact Center Users',
'SDG-Five9 non-Contact Center Users',
'SDG-FlexObjects SDK Users',
'SDG-FlexTerm 64-bit Users',
'SDG-FlexTerm RemoteLocale Users',
'SDG-Fuzzy Lookup Add-In for Excel Users',
'SDG-Git for Windows 2.30.2 Users',
'SDG-Google Chrome Users',
'SDG-Google Earth Users',
'SDG-HID Approve for Windows Users',
'SDG-HSF Client Users',
'SDG-DOMAIN Treasury Access Cert Users',
'SDG-DOMAIN Treasury Access Prod Users',
'SDG-Hyland Unity Client Users',
'SDG-InfeauxNet Users',
'SDG-InfoAccess Prod Users',
'SDG-InfoPrint AFP Workbench Viewer Users',
'SDG-InstEd Users',
'SDG-Java SE Dev Kit 8 Users',
'SDG-JDK 17.0.8 Users',
'SDG-LaserPro RDP Users',
'SDG-LeasePlus V3 Prod Users',
'SDG-Maestro Desktop 6.0.5i Users',
'SDG-Maestro Integrator and SDK Users',
'SDG-Market Axess Users',
'SDG-Maven Users',
'SDG-MiCollab Users',
'SDG-Micro Focus Excel Add-In 17.0 Users',
'SDG-Micro Focus Sprinter Users',
'SDG-Microsoft Edge WebView2 Runtime Users',
'SDG-Microsoft Script Debugger Users',
'SDG-Microsoft SQL Server 2012 Native Client Users',
'SDG-Microsoft Visual Studio Pro 2013 Users',
'SDG-Moodys Add-In for Excel Users',
'SDG-Morningstar Add-in 9.0.2 Users',
'SDG-Morningstar Direct 3.20.027 Users',
'SDG-MQ Explorer Users',
'SDG-MrWin6530 Users',
'SDG-NCR Transfer Manager Users',
'SDG-Neo4j Users',
'SDG-Noble SIPhoneBiz Agent Users',
'SDG-Noble SIPhoneBiz Manager Agent Users',
'SDG-NotepadPlusPlus Users',
'SDG-Office 365 Users',
'SDG-OnBase Prod AP Users',
'SDG-OnBase Prod Users',
'SDG-OneSource Income Tax Excel Addin Users',
'SDG-Oracle ODBC x32 Users',
'SDG-Oracle ODBC x64 Users',
'SDG-PayPlus BSA Prod Users',
'SDG-PayPlus GFX Prod Users',
'SDG-PayPlus PM Client Prod Users',
'SDG-PC Meter Connect Users',
'SDG-PDF Password Remover Users',
'SDG-PentaCalc Pro Users',
'SDG-PeopleImport Users',
'SDG-Piktochart Users',
'SDG-Plantronics Hub Users',
'SDG-Power BI Desktop RS May 2023 Users',
'SDG-ProducerPlus Users',
'SDG-Project Pro 2016 64Bit Users',
'SDG-PSexec Users',
'SDG-Putty .73 64 bit Users',
'SDG-Python 3.9.0 Users',
'SDG-R for Windows 4.2.1 Users',
'SDG-R for Windows 4.3.1 Users',
'SDG-RazorSQL 10.3 Users',
'SDG-Real-Time Monitoring Tool Users',
'SDG-Redirector Users',
'SDG-Risk Users',
'SDG-RSA SecurID Users',
'SDG-RStudio 2023.06.2 Users',
'SDG-SalesForce Chrome bookmark Users',
'SDG-Salesforce CLI Users',
'SDG-Salesforce Inspector Users',
'SDG-SecureCRT-SecureFX 9.4.1 Users',
'SDG-SilverLight Users',
'SDG-Smart View for Office Users',
'SDG-Smartcrypt Reader Users',
'SDG-SnagIt 2024 Users',
'SDG-SoapUI Users',
'SDG-SolarWinds 2000 Professional Plus Users',
'SDG-SolarWinds Toolset v11.0.1 Users',
'SDG-SpeechExec Pro Dictate Users',
'SDG-SpeechExec Transcription Users',
'SDG-SQL 2016 Report Builder Users',
'SDG-SQL Management Studio 19.3 Users',
'SDG-SQL Mobile Report Publisher Users',
'SDG-SQL Server Data Tools VS 2017 Users',
'SDG-SSMA for Access Users',
'SDG-SuperTRUMP Users',
'SDG-Synkronizer 11.1 Users',
'SDG-Tableau 2022.2 Users',
'SDG-Tableau Reader 2022.2 Users',
'SDG-TDconnect Users',
'SDG-TeamMate Analytics Users',
'SDG-TeamMate Audit Prod Users',
'SDG-TeamMate Audit Test Users',
'SDG-TeamMate Risk Prod Users',
'SDG-TeamMate Risk Test Users',
'SDG-TelSpanWeb Screen Sharing Users',
'SDG-Tic Tie Calculate Users',
'SDG-TortoiseSVN 64bit Users',
'SDG-TortoiseSVN with CLI Users',
'SDG-UFT One Add-in for ALM v22 Users',
'SDG-Ultipro 10.4.1 WNB Users',
'SDG-Vector Cash Users',
'SDG-Verint Playback Users',
'SDG-VidCenter 10.8.5 Users',
'SDG-Video Inspector Users',
'SDG-Viking IP Programming Users',
'SDG-VIP Access Users',
'SDG-Virtual Observer Agent Client Users',
'SDG-Visio Standard 2016 64bit Users',
'SDG-Visual Studio Code Users',
'SDG-Visual Studio Professional 2017 Users',
'SDG-VLC media player Users',
'SDG-WalkMe Users',
'SDG-WinMerge Users',
'SDG-WinSCP 5.17 Users',
'SDG-WinSCP3 Mortgage Users',
'SDG-WinSQL Lite Users',
'SDG-WinView32 Users',
'SDG-WinZip 27.0 Users',
'SDG-WinZip 28 Users',
'SDG-WNB Law SQL Alias Users',
'SDG-XL-Connector Users',
'SDG-XMLSpy 2020 Users'

##############################
$ADate = Get-Date -Format "yyyy_MM-dd"
$Log = "D:\Powershell\!SCCM_PS_scripts\!Collections\$ADate--SDG_Collection_Queries.csv"
"Collection Name,Query Group" | Set-Content $Log

$i = 1
$total = $Collections.count
$Collections | % {
"$i of $total -- $_"
$Check = Get-CMUserCollectionQueryMembershipRule -CollectionName "$_"
If ($check -eq $null){ '"' + $_ + ",No Query"| Add-Content $Log}
Else
{
    $Query = [string]$($Check.queryExpression)
    $SDGGroup = $query.subString('176').replace('"','').replace('DOMAIN\\','')
    If ($SDGGroup -contains '=')
    {
        '"' + $_ + '","' + $SDGGroup.split('=')[1] + '"' | Add-Content $Log 
    }
    Else
    {
        '"' + $_ + '","' + $SDGGroup + '"' | Add-Content $Log
    }
$i++
}
