# Compliance_File_Check_IF_Exists_Discovery.ps1
        $PS1File = 'C:\!Powershell\Compliance_Scripts\Compliance_Regedit_Discovery--AutoGenerated.ps1'

$RegPath1 = "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_DISABLE_IE11_SECURITY_EOL_NOTIFICATION"
$RegPath2 = "HKLM:\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_DISABLE_IE11_SECURITY_EOL_NOTIFICATION"
$RegKey1 = "iexplore.exe"
$RegKey2 = "iexplore.exe"
$RegType1 = "DWORD"
$RegType2 = "DWORD"
$RegValue1 = "1"
$RegValue2 = "1"

# Compliance Regedit - Discovery Script
try
{$UpdateCheck86 = Get-ItemProperty $RegPath1 -Name iexplore.exe
$UpdateCheck = Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_DISABLE_IE11_SECURITY_EOL_NOTIFICATION' -Name iexplore.exe
If (($UpdateCheck."iexplore`.exe" –eq 1) -and ($UpdateCheck."iexplore`.exe" –eq 1))
{Write-Host 'Compliant'}
Else{Write-Host 'Non-Compliant'}}
Catch{$_.Exception.Message}