cls

}
cls
##############################
# Add Required Type Libraries
    [System.Reflection.Assembly]::LoadFrom((Join-Path (Get-Item $env:SMS_ADMIN_UI_PATH).Parent.FullName "Microsoft.ConfigurationManagement.ManagementProvider.dll")) | Out-Null
    [System.Reflection.Assembly]::LoadFrom((Join-Path (Get-Item $env:SMS_ADMIN_UI_PATH).Parent.FullName "Microsoft.ConfigurationManagement.ApplicationManagement.dll")) | Out-Null
    [System.Reflection.Assembly]::LoadFrom((Join-Path (Get-Item $env:SMS_ADMIN_UI_PATH).Parent.FullName "Microsoft.ConfigurationManagement.ApplicationManagement.Extender.dll")) | Out-Null
    [System.Reflection.Assembly]::LoadFrom((Join-Path (Get-Item $env:SMS_ADMIN_UI_PATH).Parent.FullName "Microsoft.ConfigurationManagement.ApplicationManagement.MsiInstaller.dll")) | Out-Null
############################

C:
CD 'C:\Program Files (x86)\Microsoft Endpoint Manager\AdminConsole\bin'
Import-Module ".\ConfigurationManager.psd1"
Start-Sleep -Milliseconds 500
Set-Location XX1:
CD XX1:

##############################

$Applications = '01 - McAfee Agent',
'01 - McAfee Framework Agent',
'02 - McAfee - Agent',
'02 - McAfee - Endpoint Security Platform',
'02 - McAfee ENS Master Install',
'02 - McAfee ENS Master Installer',
'03 - McAfee - Endpoint Security Threat Prevention',
'03 - McAfee Client Proxy (MCP)',
'03 - McAfee Client Proxy 4.1.4.9',
'03 - McAfee Client Proxy',
'04 - Avecto Defendpoint Client',
'04 - McAfee - Endpoint Security Adaptive Threat Protection',
'04 - Privilege Management for Windows',
'05 - McAfee - Endpoint Security Firewall',
'05 - McAfee Adaptive Threat Protection (ATP)',
'05 - McAfee Adaptive Threat Protection',
'06 - McAfee - Client Proxy',
'06 - McAfee Client Proxy 4.1.113',
'06 - McAfee Client Proxy_4.0',
'06a - McAfee Endpoint Encryption Agent',
'06b - McAfee Drive Encryption',
'08 - McAfee - MVision',
'1099 Express Enterprise 2014',
'1099 Express Enterprise 2015',
'1099 Express Enterprise',
'8021x Hotfixes',
'ALM Microsoft Word Addin',
'ASPIRE',
'Adobe Acrobat Reader 2017 MUI',
'Anypoint Studio 6.6.10',
'Anypoint Studio 7.11.1',
'Avecto Defendpoint Client 4.1.287',
'BIG-IP_Edge_Client',
'BIOS_Precision_3560_Latitude_5520',
'Bloomberg Terminal 03082020',
'Bloomberg Terminal Old',
'Bomgar Jump Client',
'Bridger Insight XG Smart Client',
'Broadgun pdfMachine',
'CMS',
'CUDeviceManager v1.0.1.15',
'CUDeviceManager v1.0.1.25',
'CUDeviceManager v1.0.1.30',
'CUDeviceManager v4.0.0.117',
'CUDeviceManager v4.0.0.118',
'CUDeviceManager v4.0.0.119',
'CUDeviceManager v4.0.0.72',
'Carleton SmartPC',
'Cisco IronPort Encryption Plugin for TS',
'Cisco IronPort Encryption Plugin',
'Cisco Supervisor Desktop Services 8.5(2a)',
'Cisco WebEx Recorder and Player',
'Citrix Receiver',
'ClickYes',
'Cofense Reporter',
'CutePDF (Current)',
'CutePDF for TS',
'CutePDF',
'DM 5.3.1',
'Daisy',
'Datawatch Monarch 15',
'DatawatchMonarch_14.2',
'Edge Beta',
'Encompass 360 2018',
'APPLICATION01 PrintFlag.txt',
'APPLICATION01 APP2 New',
'APPLICATION01 APP2',
'APPLICATION01 Update for Production Workstations 06272020',
'APPLICATION01 Update for Production Workstations 10312017',
'APPLICATION01 Update for Production Workstations',
'APPLICATION01 Update for Training Servers',
'APPLICATION01 Update for Training Workstations 10312017',
'FIS Authenticator 1.1.2',
'FlexTerm 64-bit',
'GSplit',
'Ghostscript for CutePDF 2.71',
'HIPS Patch',
'HP Sprinter 14.1',
'Heat 8.4',
'Hyland ActiveX',
'Hyland App Enabler for AP',
'Hyland OnBase Test Client',
'Hyland OnBase Thick Client Shortcut for AP for TS',
'Hyperion Smart View for Office',
'IAOB Prod Admin Reports',
'INFO-ACCESS - Test',
'INFO-ACCESS 5.7.19050.2',
'Image Centre 2019',
'Image Centre 2021',
'Image Centre 2022',
'Image Centre 2022-copy',
'Image Centre LR8 - 2020',
'Internet Explorer 11 with Pre-Reqs',
'Internet Explorer Fixes',
'Java 6',
'Java 7u241',
'Java 8.x 32-bit - (Current)',
'Java 8.x 64-bit - (Current)',
'Java 8u231',
'Java 8u241 x64',
'Java 8u241 x86',
'Java 8u251 x64',
'Java 8u251 x86',
'KB5003173',
'KB5004237',
'KB982316',
'Kontiki Media Manager',
'MarchNetworks Evidence Apps',
'McAfee Client Proxy v2.2',
'McAfee Drive Encryption 7.2',
'McAfee Drive Encryption Agent 7.2',
'McAfee Drive Encryption Go',
'McAfee Endpoint Security Platform',
'McAfee Frame Package 5.0.5.658',
'McAfee Host Intrusion Prevention - Servers',
'Microsoft Power BI Desktop',
'Microsoft Power Query for Excel',
'Microsoft Remote Server Administration Tools',
'Microsoft To Do:Lists Tasks Reminders',
'Monarch 2020',
'Monarch',
'Morningstar Direct 3.20.017',
'Morningstar Direct 3.20.019',
'Morningstar Direct 3.20.020',
'Nasdaq OfficeSuite',
'Navco Retrieval 2.7.0',
'NotepadPlusPlus 7.4.2',
'Notepadplusplus 7.5.1',
'Office 2010 Pro Plus',
'Office 2013 Pro Plus w SP1 32bit for TS',
'Office 2013 Pro Plus w SP1 64bit',
'Office 365 Current Channel v2201',
'Office Professional Plus 2016 (32-bit)',
'Office Professional Plus 2016 (64-bit) for TS',
'OnBase Client for AP',
'OnBase Client',
'OneDrive WinSxS Fix',
'Opera Browser',
'Oracle Hyperion Smart View 11.1.2.2.310',
'PCFinder',
'PCOMM 6.05',
'PF Batch Export 4.0.21266.1',
'PF Batch Export OLD',
'PF Batch Export',
'Password Reset Desktop Integration for TS',
'PasswordResetProxyFix',
'Password_Reset_Desktop_Integration',
'PeopleTools 8.52',
'PhishMe Outlook AddIn',
'Power Query for Excel',
'PowerPivot 11 for Excel  32-bit',
'Printer Logic Client',
'PrinterLogic Extension',
'PrinterLogic Extension-copy',
'Privilege Management for Windows (x64) 21.6.153.0',
'Project Pro 2013 64bit',
'Project Pro 2013',
'QA4',
'Report Builder 3.0',
'Retired-Change PC Name during OSD',
'Retired-Internet Explorer 11',
'Retired-McAfee Encryption Agent',
'Retired-McAfee FramePackage Agent',
'Retired-Veritas Enterprise Vault Outlook Add-in',
'Retired-WinSCP',
'SQL Management Studio 2012 32bit',
'SQL Management Studio 2012 64bit',
'Safari 5.1',
'APP1 Base Install',
'APP1 Tweaks',
'APP1 Host Update',
'SentinelOne Agent - Servers',
'Server 2012 R2 Update Stack',
'Skype Meetings App',
'Skype for Business 2015 64bit',
'Skype for Business 2015',
'Snow Inventory Agent Test',
'Snow Inventory Agent_Test_6.5.0',
'Symantec AgentInstall-x64_15_8 UPGRADE ONLY',
'Symantec AgentInstall-x64_15_8',
'Symantec DLP Agent',
'TCC Main',
'TeamMate AM 12.3 Audit Prod',
'TeamMate AM 12.3 Audit Test',
'TeamMate AM 12.3 Desktop',
'TeamMate AM 12.3 Risk Prod',
'TeamMate AM 12.3 Risk Test',
'TrustDesk Update 12.15.00',
'TrustDesk',
'UnInstall Symantec EVault 10.0.1',
'Uninstall Java 8u241 x64',
'Unity Client',
'VDI-DR shortcut',
'Veritas Enterprise Vault Discovery Accelerator Client 12.4.0.1105',
'Veritas Enterprise Vault Discovery Accelerator Client 14.1.1.1165',
'Veritas Enterprise Vault Outlook Add-in 12.4',
'Veritas Enterprise Vault Outlook Add-in 14.2.0.1226',
'Vid-Center',
'VidCenter 10.8.5',
'Video Inspector 13.0.5',
'Video Inspector',
'Visio Standard 2013',
'Visio Standard 2016 32bit',
'Visual Studio Code 1.64.0',
'Visual Studio Code',
'WSS Agent',
'WalkMe',
'WebEx Recorder and Player Uninstall',
'WinMerge',
'WinZip 24',
'Windows 10 Admin Kit 1803',
'Windows Management Framework 5.0',
'Workshare Professional for TS',
'Workshare Professional',
'iGel Universal Management Suite'
#################################################################
#################################################################

$ADate = Get-Date -Format "yyyy_MM-dd"
$i = 1
$total = $applications.count
ForEach ($Application in $Applications)
{
    "$i of $total -- deleting $Application..."

    $CMApp = Get-CMApplication -Name $Application
    $DistStatus = Get-CMDistributionStatus -Id $($CMApp.PackageID)

    If (($($DistStatus.Targeted -eq 0)) -and
        ($($DistStatus.NumberErrors -eq 0)) -and
        ($($DistStatus.NumberInProgress -eq 0)) -and
        ($($DistStatus.NumberSuccess -eq 0)))
    {
        Write-Host "$i of $total -- $Application has no distributed content - deleting" -f Green
        # Remove-CMApplication -InputObject $CMApp -Force
    }
    Else { Write-Host "$i of $total -- $Application --- Found Content" -f Red }
    $i++
}

