# Compliance Check if file exists - Remediation
 # Compliance Check if file exists - Remediation
    $PS1File = 'C:\!Powershell\Compliance_Scripts\Compliance_Regedit_Remediation--AutoGenerated.ps1'
    '# Compliance Regedit - Remediation Script' | Add-Content $PS1File
    '$RegPath1 = "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_DISABLE_IE11_SECURITY_EOL_NOTIFICATION"' | Add-Content $PS1File
    '$RegPath2 = "HKLM:\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_DISABLE_IE11_SECURITY_EOL_NOTIFICATION"' | Add-Content $PS1File
    '$RegKey1 = "iexplore.exe"' | Add-Content $PS1File
    '$RegKey2 = "iexplore.exe"' | Add-Content $PS1File
    '$RegType1 = "DWORD"' | Add-Content $PS1File
    '$RegType2 = "DWORD"' | Add-Content $PS1File
    '$RegValue1 = "1"' | Add-Content $PS1File
    '$RegValue2 = "1"' | Add-Content $PS1File
    'try' | Add-Content $PS1File
    '{if ((test-path $RegPath1) -ne $true)' | Add-Content $PS1File
    '{New-Item $RegPath1 -Force}' | Add-Content $PS1File
    'Set-ItemProperty $RegPath1 -Name $RegKey1 -Type $RegType1 -Value $RegValue1 -Force}' | Add-Content $PS1File
    'Catch{$_.Exception.Message}' | Add-Content $PS1File
    'try' | Add-Content $PS1File
    '{if ((test-path $RegPath2) -ne $true)' | Add-Content $PS1File
    '{New-Item $RegPath2 -Force}' | Add-Content $PS1File
    'Set-ItemProperty $RegPath2 -Name $RegKey2 -Type $RegType2 -Value $RegValue2 -Force}' | Add-Content $PS1File
    'Catch{$_.Exception.Message}' | Add-Content $PS1File